SDP/prolancers/spike/redirect_example/config/routes.rb
Rails.application.routes.draw do

  get "signin/redirect"
  get "greeter/index"

  resources :signin, :only => [:index] do
    collection do
      get :signout
    end
  end
end

SDP/prolancers/spike/redirect_example/app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  include ApplicationHelper
  
  before_action :check_signed_in, only: [:index]
  
  def index 
  end
  
  def hello
  end
end

SDP/prolancers/spike/redirect_example/app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def index
    
  end

  def redirect
  	session[:user] = params[:user_id]
  	redirect_to session[:referer]     
  end              
  
  def signout
    session[:user] = nil
  end
end

SDP/prolancers/spike/redirect_example/app/helpers/application_helper.rb
module ApplicationHelper
  def check_signed_in
    if session[:user] == nil
      if request.format.html?
        session[:referer] = request.url
        redirect_to signin_index_path
      else
        render 'signin/show_signin.js'
      end      
    end
  end
end

SDP/prolancers/spike/redirect_example/app/helpers/greeter_helper.rb
module GreeterHelper
end

SDP/prolancers/spike/redirect_example/app/helpers/signin_helper.rb
module SigninHelper
end

SDP/prolancers/spike/redirect_example/app/views/greeter/hello.js.erb
alert("hello there, go to signin/signout to log out");

SDP/prolancers/spike/redirect_example/app/views/greeter/index.html.erb
Greetings

<%= link_to 'hello', greeter_index_path, remote: true %>

<p></p>

<p><%= link_to 'signout', signout_signin_index_path %></p>

SDP/prolancers/spike/redirect_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedirectExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>